name: CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ] # ubuntu-latest
        buildType: [ Debug, Release ]

    name: ${{ matrix.os }} - ${{ matrix.buildType }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v7

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: x64
      
      - name: Configure
        run: cmake . -B__build -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.buildType }}
      
      - name: Build
        run: cmake --build __build --parallel

      - name: Package
        run: cmake --build __build --target package

      - name: Upload artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v7
        with:
          name: JUCE-PreCompiled-${{ matrix.os }}-${{ matrix.buildType }}
          path: "__build/__package/*.tar.gz"
          if-no-files-found: error

      - name: Upload to GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          files: "__build/__package/*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
