name: CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v7
      
      - name: Configure
        run: cmake . -B__build -GNinja -DCMAKE_BUILD_TYPE=Release
      
      - name: Build
        run: cmake --build __build --parallel

      - name: Package
        run: cmake --build __build --target package

      - name: Upload artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v7
        with:
          name: ClapWorkbenchSDK-${{ matrix.os }}
          path: "__build/__package/*.tar.gz"
          if-no-files-found: error

      - name: Upload to GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          files: "__build/__package/*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
